### ISSUE TITLE
Failure mapping core_7-0-0 insurance procedure from prod CSV importer

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/collectionspace-mapper#123]
```
undefined method `dig' for #<String:0x00007fc0ad10da40> -- /app/vendor/bundle/ruby/2.7.0/bundler/gems/collectionspace-mapper-ff839d011340/lib/collectionspace/mapper/term_searchable.rb:151:in `response_term_refname'
```
[insurance.csv](https://github.com/collectionspace/collectionspace-mapper/files/7023948/insurance.csv)

**Comment by kspurgin** [comment]
Ugh, I'm unable to catch a Heroku log message on this, and unable to reproduce in local dev environment.

**Comment by kspurgin** [comment]
Ok, I have updated the tests in collectionspace/collectionspace-client and they all still work with 7.0

**Comment by kspurgin** [comment]
My spidey sense on this being related to collectionspace/collectionspace-csv-importer#110 was WRONG.

I can no longer duplicate this error, so going to chalk it up to there having been something out of sync in the whole toolchain (?)
